### ISSUE TITLE
Erro: The parameter 'payment.document' was not supplied.

### ISSUE THREAD

**Issue by romuloctba** [ebanx-integration/ebanx-woocommerce#1]
When checking out I was able to provide CPF, since using the WOOCOMMERCE EXTRA CHECKOUT FIELDS FOR BRAZIL.

At the CreditCard screen, it does not ask for CPF neither RG

When performing the post, got 
`Erro: The parameter 'payment.document' was not supplied.`

I am pretty sure it happens because the docment does not go with the request.

Any helps?

**Comment by hdolinski** [comment]
this issue was corrected in the following commit:
https://github.com/ebanx-integration/ebanx-woocommerce/commit/123553ff45743431ea5f3b8d96dd8e3be800a87d#diff-9117b5b582b01f0649e15f2bb898063fR481

Are you using the latest version of the module?

**Comment by romuloctba** [comment]
Oh, sorry, I thought the Official release @ WordPress Plugin directory would be updated

My bad, just cloned this repo and worked (at sandbox, at least... I guess it should work in production)

Thank you very much
